# Generated by Django 6.0.6 on 2026-06-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('bannerid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.CharField(blank=True, max_length=300, null=True)),
                ('device', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('both', 'Both')], default='both', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
