# Generated by Django 6.0.6 on 2026-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('festival', 'Festival')], default='hero', max_length=20),
        ),
    ]
