# Generated by Django 6.0.6 on 2026-06-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_productstyle'),
        ('products', '0002_product_is_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.productstyle'),
        ),
    ]
