# Generated by Django 6.0.6 on 2026-06-17 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
        ),
    ]
